#!/bin/sh

# Note: A cmake file in your CISM build dir needs to
# be run once, before using this script.

CHOMBO_DIR=${PWD}/../../../Chombo
BISICLES_DIR=${PWD}/../../../BISICLES
CISM_DIR=${PWD}/../../../seacism


CISM_CMAKE_BUILD_DIR=${CISM_DIR}/builds/linux-gnu-bisicles

# Note: If this is the first CISM build, uncomment the following 3 lines:
#source /etc/profile.d/modules.sh
cd ${CISM_CMAKE_BUILD_DIR}
#source linux-gnu-bisicles-cmake

cd ${CHOMBO_DIR}/lib
make include

cd ${BISICLES_DIR}/code/exec2D
make lib MPI=TRUE OPT=FALSE DEBUG=TRUE
make driver MPI=TRUE OPT=FALSE DEBUG=TRUE

cd  ${BISICLES_DIR}/code/interface
make -f GNUmakefile libs MPI=TRUE OPT=FALSE DEBUG=TRUE

cd ${CISM_CMAKE_BUILD_DIR}
rm example-drivers/simple_bisicles/src/simple_bisicles
make 

#move to seacism bin directory for convenience
mkdir -p ${CISM_DIR}/bin #this directory doesn't always exist...
mv ${CISM_CMAKE_BUILD_DIR}/example-drivers/simple_bisicles/src/simple_bisicles ${CISM_DIR}/bin

cd ${BISICLES_DIR}/code/interface

echo "NOTE: The simple_bisicles executable will be located in: "
echo "${CISM_DIR}/bin/simple_bisicles"

# used for autotools-based simple_bisicles build:
#cd ~/glimmer-cism2/branches/seacism/libdycore
#make -f Makefile.hopper libDyCoreToGlimmer.a
#cd ~/glimmer-cism2/branches/seacism/example-drivers/simple_bisicles/src
#make -f Makefile.hopper simple_bisicles
#cd ~/BISICLES/code/interface

